# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  railstest:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12.1-alpine
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
        with:
          ruby-version: '3.1.0'
      - name: Install dependencies
        run: bundle install
      - name: Create test database
        run: bundle exec rails db:create
      - name: Run migrations
        run: bundle exec rails db:migrate
      - name: Run test
        run: bundle exec rspec
      - uses: actions/setup-node@v1
      - name: Set up NextJS
      with:
        node-version: 16
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install JS dependencies
        working-directory: ./client
        run: yarn install --frozen-lockfile
      - name: Build JS bundle
        working-directory: ./client
        run: yarn build
      - name: Run JS tests
        working-directory: ./client
        run: yarn test

  jstest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up NextJS
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install JS dependencies
        working-directory: ./client
        run: yarn install --frozen-lockfile
      - name: Build JS bundle
        working-directory: ./client
        run: yarn build
      - name: Run JS tests
        working-directory: ./client
        run: yarn test
